const DESKTOP_RESOLUTION = 1280;
const TABLET_RESOLUTION = 768;
const MOBILE_RESOLUTION = 320;
const SHORT_MOVIE_DURATION = 40;

export {
  DESKTOP_RESOLUTION,
  TABLET_RESOLUTION,
  MOBILE_RESOLUTION,
  SHORT_MOVIE_DURATION
}
